#!/bin/bash

# incoming 
alias sxhkd="vim $HOME/.config/sxhkd"
alias bspwm="vim $HOME/.config/bspwm"
alias sx="sxhkd"
alias bs="bspwm"
alias aliases="vim $HOME/.config/aliases && source $HOME/.config/aliases"
alias rc="vim $HOME/.config/rc"
alias profile="vim $HOME/.config/profile"

alias ls='ls --color=auto'
alias la='ls -l --color=auto'
alias lal='ls -al --color=auto'
alias l='ls'
alias s='ls -r'

alias please='sudo "$BASH" -c "$(history -p !!)"'

alias status='git status'
alias commit='git commit'
alias addg='git add'
alias diffg='git diff'

# General
alias v="vim"
alias vv="vim ."

alias plan='vim +set\ ft=todo ~/.plan'
alias adventure='vim "~/adventures/$(date).txt"'
alias today='date;cal'

alias vimrc='vim .vim/vimrc'
alias zshrc='vim .zshrc'
alias stows='vim ~/doftiles'

alias s="ls -tr -1h --color=tty"
alias sl="ls -r"
alias ll="ls -rlAt -1h --color=tty"
alias l="ls -tAh -1"

# Windows
alias explorer="explorer.exe"

# Arch Linux
alias ayy="yay -S"
alias yeet="yay -Rns"
alias hc=herbstclient

# Files
alias cd..="cd .."
alias ..="cd .."
alias cp="cp -vi"
alias df=duf
alias open=xdg-open
alias sysc=systemctl

# Mess
# /home/kine/.bin/tasks
# /home/kine/.bin/adventure
alias done="todo -r"
#alias task="todo -a"
alias ff="find ~/ | fzf"
alias fwhich="which-file"
alias lb_navigate='cd ${LOCAL_BIN}'
alias lls="readlink -e"
alias netmum='nload -m u m'
alias pgrep="pgrep -l"
alias please='please "$(fc -ln -1)"'
alias ppid='ps -o ppid=,cmd= -p'
alias preview="fzf --preview 'bat --color \"always\" {}'"
alias ri="rm -ri"
alias root_from_boot='journalctl -b | grep -i sudo'
alias rr="rm -r"
alias rf="rm -f"
alias show=bat
alias ss="please ss"
alias sude="sudo -E su"
alias sudi="sudo -i"
alias tasks_session='vim --servername tasks'
alias up=uprecords
alias winefy='export WINEARCH=win64 WINEPREFIX=`pwd`'

# Todo
alias last="echo vim expansion for edit last file"
#alias la="ls -l|grep --color \"->\"|sed -e 's/->\(.*\)/\n->\1/g'"

# SSH
alias surface='ssh surface'
alias portable='ssh portable'

