#!/usr/bin/env bash

herb() {
    herbstclient "$@"
}

keyreg() {
	herb keybind "$@"
}

### CONFIG ###
export MONITORS=$(herb detect_monitors -l | wc -l)

### MODS ###
Mod=Mod4   	# Super
ModAlt=Mod1 # Alt 

### ADDITIONAL MODS ###
ModAlt2=$ModAlt-Ctrl 
ModShift=$Mod-Shift
ModCtrl=$Mod-Ctrl

### REGISTER RELOAD ###
herb emit_hook reload
herb set_layout max
herb keyunbind --all
polybar single &

# LAUNCHERS
TERMINAL="gnome-terminal --zoom 1.5"
ROFITHEME=${HOME}/.config/rofi/launcher/style.rasi
APPLAUNCHER="rofi -modi drun,run -show drun -theme ${ROFITHEME}"
SCREENSHOTTER="scrot"
APPSWITCHER="rofi -modi windowcd -show windowcd -theme ${ROFITHEME}"

# terminal
keyreg $Mod-Tab 		spawn $APPSWITCHER
keyreg $Mod-Return              spawn $TERMINAL
# applauncher
keyreg $Mod-BackSpace			spawn $APPLAUNCHER
# screenshot; revision HHKB custom caps
keyreg $Mod-o           		spawn $SCREENSHOTTER


# CLOSE OR QUIT WM
keyreg $Mod-q					close_or_remove
keyreg $ModShift-q				remove
keyreg $ModCtrl-q				spawn xkill
keyreg $Mod-Escape				reload
keyreg $Mod-w					reload
keyreg $ModShift-Escape			quit
# for linux
keyreg XF86Sleep				quit

# WINDOWING
keyreg $ModShift-Return		chain . split explode . cycle_frame . spawn $TERMINAL
keyreg $Mod-a				chain . split explode 0.5 . cycle_frame
keyreg $ModShift-a			chain . split vertical . cycle_frame
keyreg $ModShift-d			remove

# cycle; TODO: make these cycle frame if only in frame
keyreg $Mod-s 		chain \
						. cycle -1
keyreg $ModShift-s	chain \
						. cycle +1
keyreg $Mod-c		cycle_frame

keyreg $ModAlt-Tab		or \
					, and \
						. compare tags.focus.curframe_wcount gt 1 \
						. cycle +1 \
					, cycle_frame 

keyreg $Mod-d	or						 \
	, and                 						 \
		. compare tags.focus.curframe_wcount = 2 \
		. cycle_layout +1 max grid vertical      \
	, cycle_layout +1 horizontal grid vertical max

# rotate layout
keyreg $ModCtrl-c			rotate
# flip layout
keyreg $ModShift-c			chain , lock , rotate , rotate , unlock
# split into direction
keyreg $Mod-v				split right  0.5
keyreg $Mod-b				split bottom   0.5
keyreg $ModCtrl-v			chain , split right  0.5 , focus -e right
keyreg $ModCtrl-b			chain , split bottom   0.5 , focus -i down
keyreg $ModShift-b			chain split top   0.5 , focus -i down



# FOCUS
keyreg $Mod-Left       focus left
keyreg $Mod-Down       focus down
keyreg $Mod-Up         focus up
keyreg $Mod-Right      focus right
keyreg $ModAlt-h          focus left
keyreg $ModAlt-j          focus down
keyreg $ModAlt-k          focus up
keyreg $ModAlt-l          focus right
keyreg $ModCtrl-Left  shift left
keyreg $ModCtrl-Down  shift down
keyreg $ModCtrl-Up    shift up
keyreg $ModCtrl-Right shift right
keyreg $ModCtrl-h     shift left
keyreg $ModCtrl-j     shift down
keyreg $ModCtrl-k     shift up
keyreg $ModCtrl-l     shift right

### TAGS ###
#TODO: create a script to tag programs with Mod-T

# focus tag instead of bringing it
herb set swap_monitors_to_get_tag 0

#function verb() {
#	action=$1
#	src=$2
#	dst=$3
#	mon=0
#	echo "chain . lock . focus_monitor $mon . $action $src . cycle_monitor . $action $dst . focus_monitor $mon . unlock"
#}

tag_names=( work term browser task )
tag_keys=( {1..9} 0 )

herb rename default "${tag_names[0]}" || true
for i in "${!tag_keys[@]}" ; do
	if ! [ -z $name ] ; then
		herb add "${tag_names[$i]}"
	fi
	key="${tag_keys[$i]}"
	if [ -n "$key" ] ; then
		herb keybind "$Mod-$key" use_index "$i"
		herb keybind "$Mod-Shift-$key" move_index "$i"
	fi
done


keyreg $Mod-x use_previous
# substitute last window from mod-w
	
# mouse
herb mouseunbind --all
herb mousebind $Mod-Button1 move
herb mousebind $Mod-Button2 zoom
herb mousebind $Mod-Button3 resize


# focus other screen
keyreg $Mod-e      cycle_monitor
# send to other screen
keyreg $ModCtrl-e shift_to_monitor +1
# swap with other screen
#keyreg $ModCtrl-e chain . lock .  . unlock
#keyreg $ModShift-x use_index -1 --skip-visible
keyreg $ModShift-x spawn bring_last
keyreg $ModShift-e spawn swap_monitors 0

source /home/kine/.config/herbstluftwm/dunst_keybinds

#
# resizing frames and floating clients
resizestep=0.25
##nudgestep=.25
nudgestep=0.083
# keyreg $ModCtrl-comma           resize left +0.05
# keyreg $ModCtrl-period          resize right +0.05
keyreg $Mod-bracketleft  use_index -1 --skip-visible
keyreg $Mod-bracketright use_index +1 --skip-visible

keyreg $ModCtrl-comma    resize left +$resizestep
keyreg $ModCtrl-period   resize right +$resizestep

keyreg $ModShift-h       resize left +$nudgestep
keyreg $ModShift-j       resize down +$nudgestep
keyreg $ModShift-k       resize up +$nudgestep
keyreg $ModShift-l       resize right +$nudgestep
keyreg $ModShift-Left    resize left +$resizestep
keyreg $ModShift-Down    resize down +$resizestep
keyreg $ModShift-Up      resize up +$resizestep
keyreg $ModShift-Right   resize right +$resizestep

herb set default_direction_external_only
                                     
keyreg $Mod-comma       cycle_all --skip-invisible -1
keyreg $Mod-period      cycle_all --skip-invisible +1
keyreg $ModShift-comma  shift left
keyreg $ModShift-period shift right
                                     
# maximize
keyreg $Mod-f fullscreen toggle
keyreg $ModShift-space                    chain . set_attr clients.focus.floating off . pseudotile toggle . jumpto urgent
# resize popup                       
keyreg $ModCtrl-space                chain \
                                        , set_attr clients.focus.floating toggle \
                                        , pseudotile off
keyreg $Mod-space   	              chain \
                                        , lock \
                                        , attr tags.focus.floating_focused toggle \
										, cycle , cycle -1 \
                                        , unlock
# peek grid
keyreg $ModCtrl-z cycle_layout +1 grid max
# peek floats
keyreg $ModShift-z     floating toggle
keyreg $Mod-z 	spawn throw_corner

# keybind move mouse to center window and pop up lemonbar / rofi / dmenu

keyreg $Mod-i     bring urgent

## TODO: change to bring to last tag
#keyreg $ModShift-x jumpto urgent


# THEME
herb attr theme.tiling.reset 1
herb attr theme.floating.reset 1

#= COLOURS =#
herb set frame_border_active_color '#666'
herb set frame_border_normal_color '#333'
herb set frame_bg_normal_color '#88888800'
herb set frame_bg_active_color '#eee'
herb attr theme.active.color '#feef69'
herb attr theme.normal.color '#666'
herb attr theme.urgent.color orange
herb attr theme.minimal.color '#333'
herb attr theme.floating.outer_color '#97ff65'
herb attr theme.active.inner_color '#ffeeee'
herb attr theme.active.outer_color '#feef69'
herb attr theme.background_color '#333333'
#herb attr theme.floating.outer_color '#00ef69'
#herb attr theme.floating.outer_color '#aaef69'

herb set always_show_frame off
herb set frame_bg_transparent on
herb set frame_transparent_width 2
herb set frame_border_width 5

# ????
herb set frame_gap 0
#herb set frame_gap -10
herb set window_gap 0
herb set frame_padding 0

herb set snap_distance 10
herb set snap_gap 5

herb set smart_window_surroundings off
herb set smart_frame_surroundings off

herb attr theme.minimal.border_width 2
herb attr theme.inner_width 0
herb attr theme.inner_color black
herb attr theme.border_width 5
herb attr theme.floating.border_width 5
herb attr theme.floating.outer_width 5

herb set mouse_recenter_gap 5
herb set focus_follows_mouse 1
# +git commit # turn setting wrong
herb set focus_crosses_monitor_boundaries off
herb set gapless_grid on
herb set hide_covered_windows on
herb set pseudotile_center_threshold 25
herb set update_dragged_clients 0
#herb set raise_on_focus on

# rules
herb unrule -F
#herb rule class=XTerm tag=3 # move all xterms to tag 3
herb rule focus=on # normally focus new clients
herb rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
herb rule class~'[Yy]ad' floating=on
herb rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
herb rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off focus=off

herb add term
herb add config
herb add task
herb add browser
herb add discord
herb rule class='pavucontrol' tag=volume
herb rule class='spotify' tag=music
herb rule class='firefox' windowtype='_NET_WM_WINDOW_TYPE_NORMAL' tag=browser
herb rule title='Task Manager' tag=task
herb rule title='Config Manager' tag=config

keyreg $ModShift-p   chain , spawn sh -c 'pidof pavucontrol || pavucontrol' , use volume
keyreg $ModShift-m   chain , spawn sh -c 'pidof spotify || spotify' , use music
keyreg $Mod-m        spawn spotify_playpause
keyreg $Mod-n        spawn spotify_control next
keyreg $ModShift-n   spawn spotify_control previous
keyreg XF86AudioPlay spawn spotify_playpause
keyreg XF86AudioNext spawn spotify_control next
keyreg XF86AudioPrev spawn spotify_control previous

herb rule class='discord' tag=discord

herb rule class='tasks' floating=on
keyreg $Mod-t 		spawn task_window

herb set tree_style '╾│ ├└╼-┐'
herb set default_frame_layout 1

# unlock, just to be sure
herb unlock

# do multi monitor setup here, e.g.:
# herb set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
herb detect_monitors
